In [11]:
import pandas as pd

In [12]:
a1 = pd.read_csv('data1.csv', dtype=str)

In [13]:
a2 = pd.read_csv('data2.csv', dtype=str)

In [14]:
a3 = pd.read_csv('data3_20260711.csv', dtype=str)

In [15]:
a4 = pd.read_csv('data3_20260711_2.csv', dtype=str)

In [16]:
a5 = pd.read_csv('data3_20260711_3.csv', dtype=str)

In [17]:
a6 = pd.read_csv('data_20260712_1.csv', dtype=str)

In [18]:
a = pd.concat([a1,a2, a3,a4,a5,a6]).drop_duplicates()

In [19]:
a

,st_save_date,st_event_name,st_event_date,st_kafka_offset,st_source_type,st_app_key,st_raw_message,st_available_message,st_status,st_error_type,st_error_info,st_report_time,st_update_at,st_save_time
0,2026-07-10,log_page_expose_client,2026-07-10,11_592,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_event_name"":""log_page_expose_client"",""st_...","{""st_event_name"":""log_page_expose_client"",""st_...",3,3,"{""3"":[""属性名【model_name】在埋点方案中不存在""]}",1783651398622,2026-07-10 02:43:18.702838,1783651397000
1,2026-07-10,st_users,2026-07-10,5_0,user,618025f4e02aff8f3e35df5d2891cc47,"{""st_role_id"":""33"",""st_event_time"":17836530477...","{""st_role_id"":""33"",""st_event_time"":17836530477...",3,3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...",1783653050499,2026-07-10 03:10:50.551381,1783653048000
2,2026-07-10,st_users,2026-07-10,4_44,user,618025f4e02aff8f3e35df5d2891cc47,"{""st_account_id"":""14"",""st_role_id"":""14"",""st_sa...","{""st_account_id"":""14"",""st_role_id"":""14"",""st_sa...",3,3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...",1783656019446,2026-07-10 04:00:19.529169,1783656018000
3,2026-07-10,log_token_consume_server,2026-07-10,7_649,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""properties"":{""window_id"":""9ab7666b-d232-4c03...","{""st_save_time"":1783656369,""st_type"":""track"",""...",3,3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...",1783656370779,2026-07-10 04:06:10.851041,1783656369000
4,2026-07-10,log_credits_server,2026-07-10,6_644,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""properties"":{""action"":""api_call"",""platform_t...","{""st_save_time"":1783655706,""st_role_id"":""14"",""...",3,3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...",1783655707746,2026-07-10 03:55:07.829833,1783655706000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,2026-07-12,log_page_leave_client,2026-07-12,4_1593,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_pk_id"":""6ef02d59-eb05-4796-b9e4-a9a37f2bd...",NaN,1,NaN,{},1783825791131,2026-07-12 03:09:51.179104,1783825789000
46,2026-07-12,log_click_client,2026-07-12,11_1653,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_province"":""四川省"",""st_user_id"":""0000e86c-6d...",NaN,1,NaN,{},1783825792133,2026-07-12 03:09:52.179751,1783825789000
47,2026-07-12,log_page_expose_client,2026-07-12,5_1695,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_country_code"":""CN"",""st_event_name"":""log_p...",NaN,1,NaN,{},1783825747802,2026-07-12 03:09:07.851640,1783825744000
48,2026-07-12,log_element_expose_client,2026-07-12,9_1547,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_role_id"":"""",""st_save_time"":1783825748,""st...",NaN,1,NaN,{},1783825751121,2026-07-12 03:09:11.153726,1783825748000
49,2026-07-12,log_page_expose_client,2026-07-12,6_1671,event_track,618025f4e02aff8f3e35df5d2891cc47,"{""st_distinct_id"":""fab31f5b-0fed-490e-b32f-54d...",NaN,1,NaN,{},1783825791156,2026-07-12 03:09:51.179224,1783825789000

In [22]:
a.columns

Index(['st_save_date', 'st_event_name', 'st_event_date', 'st_kafka_offset',
       'st_source_type', 'st_app_key', 'st_raw_message',
       'st_available_message', 'st_status', 'st_error_type', 'st_error_info',
       'st_report_time', 'st_update_at', 'st_save_time'],
      dtype='object')

In [23]:
col = ['st_event_name', 'st_raw_message', 'st_status', 'st_error_info', 'st_available_message']

In [25]:
a = a[col]

In [26]:
a

,st_event_name,st_raw_message,st_status,st_error_info,st_available_message
0,log_page_expose_client,"{""st_event_name"":""log_page_expose_client"",""st_...",3,"{""3"":[""属性名【model_name】在埋点方案中不存在""]}","{""st_event_name"":""log_page_expose_client"",""st_..."
1,st_users,"{""st_role_id"":""33"",""st_event_time"":17836530477...",3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...","{""st_role_id"":""33"",""st_event_time"":17836530477..."
2,st_users,"{""st_account_id"":""14"",""st_role_id"":""14"",""st_sa...",3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...","{""st_account_id"":""14"",""st_role_id"":""14"",""st_sa..."
3,log_token_consume_server,"{""properties"":{""window_id"":""9ab7666b-d232-4c03...",3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...","{""st_save_time"":1783656369,""st_type"":""track"",""..."
4,log_credits_server,"{""properties"":{""action"":""api_call"",""platform_t...",3,"{""3"":[""属性名【utm_source】在埋点方案中不存在"",""属性名【channel】...","{""st_save_time"":1783655706,""st_role_id"":""14"",""..."
...,...,...,...,...,...
45,log_page_leave_client,"{""st_pk_id"":""6ef02d59-eb05-4796-b9e4-a9a37f2bd...",1,{},NaN
46,log_click_client,"{""st_province"":""四川省"",""st_user_id"":""0000e86c-6d...",1,{},NaN
47,log_page_expose_client,"{""st_country_code"":""CN"",""st_event_name"":""log_p...",1,{},NaN
48,log_element_expose_client,"{""st_role_id"":"""",""st_save_time"":1783825748,""st...",1,{},NaN
49,log_page_expose_client,"{""st_distinct_id"":""fab31f5b-0fed-490e-b32f-54d...",1,{},NaN

In [27]:
a.to_csv('data.csv', index=False)